[package]
name = "miso-workflow-types"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre.workspace = true
futures-util.workspace = true
hashbrown.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
time.workspace = true
